-- MySQL Script generated by MySQL Workbench
-- Tue Feb 15 14:33:09 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_construindo_a_nossa_vida
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_construindo_a_nossa_vida
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_construindo_a_nossa_vida` DEFAULT CHARACTER SET utf8 ;
USE `db_construindo_a_nossa_vida` ;

-- -----------------------------------------------------
-- Table `db_construindo_a_nossa_vida`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_construindo_a_nossa_vida`.`tb_categoria` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `observacao` VARCHAR(255),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `db_construindo_a_nossa_vida`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_construindo_a_nossa_vida`.`tb_produto` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `preco` DECIMAL(8,2) NOT NULL,
  `quantidade` INT NULL,
  `peso_kg` DECIMAL(8,2) NOT NULL,
  `dimensoes` VARCHAR(255) NOT NULL,
  `tb_categoria_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_produto_tb_categoria_idx` (`tb_categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_tb_categoria`
    FOREIGN KEY (`tb_categoria_id`)
    REFERENCES `db_construindo_a_nossa_vida`.`tb_categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

LOAD DATA LOCAL INFILE 'C:/Users/User/Documents/db_MySQL//Exercicios/14.02.22/tb_categoria_atividade05.csv'
INTO TABLE tb_categoria FIELDS TERMINATED BY ";"
ENCLOSED BY '"' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE  'C:/Users/User/Documents/db_MySQL//Exercicios/14.02.22/tb_produto_atividade05.csv'
INTO TABLE tb_produto FIELDS terminated by ";"
enclosed by '"' LINES terminated by '\n';

select * from tb_produto where preco > 50;

select * from tb_produto where preco between 3 and 60;

select * from tb_produto where nome like "%c%";

select * from 
tb_produto inner join tb_categoria
on tb_produto.tb_categoria_id = tb_categoria.id;

select * from tb_produto where tb_categoria_id = 1;





