-- MySQL Script generated by MySQL Workbench
-- Tue Feb 15 13:15:22 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_cidade_das_frutas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cidade_das_frutas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cidade_das_frutas` DEFAULT CHARACTER SET utf8 ;
USE `db_cidade_das_frutas` ;

-- -----------------------------------------------------
-- Table `db_cidade_das_frutas`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cidade_das_frutas`.`tb_categoria` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(255) NOT NULL,
  `beneficio` VARCHAR(255) NOT NULL,
  `observacao` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cidade_das_frutas`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cidade_das_frutas`.`tb_produto` (
  `id` BIGINT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `quantidade` BIGINT NULL,
  `preco` DECIMAL(8,2) NOT NULL,
  `cor` VARCHAR(255) NOT NULL,
  `validade` DATE NOT NULL,
  `tb_categoria_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_produto_tb_categoria_idx` (`tb_categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_tb_categoria`
    FOREIGN KEY (`tb_categoria_id`)
    REFERENCES `db_cidade_das_frutas`.`tb_categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

LOAD DATA LOCAL INFILE 'C:/Users/User/Documents/db_MySQL/aula_04/tb_produtos.csv'
INTO TABLE tb_produto FIELDS TERMINATED BY ';'
ENCLOSED BY '"' LINES TERMINATED BY '\n';

select * from tb_produto where preco > 50;

select * from tb_produto where preco between 3 and 60;

select * from tb_produto where nome like "%c%";

select * from 
tb_produto inner join tb_categoria
on tb_produto.tb_categoria_id = tb_categoria.id;

select * from tb_produto where tb_categoria_id = 1;



