-- MySQL Script generated by MySQL Workbench
-- Tue Feb 15 21:15:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_cursoDaMinhaVida
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cursoDaMinhaVida
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cursoDaMinhaVida` DEFAULT CHARACTER SET utf8 ;
USE `db_cursoDaMinhaVida` ;

-- -----------------------------------------------------
-- Table `db_cursoDaMinhaVida`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cursoDaMinhaVida`.`tb_categoria` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `periodo` VARCHAR(255) NOT NULL,
  `carga_horaria` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cursoDaMinhaVida`.`tb_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cursoDaMinhaVida`.`tb_curso` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `valor` DECIMAL(8,2) NOT NULL,
  `vagas` int not null,
  `professor` VARCHAR(255) NOT NULL,
  `dias_da_semana` VARCHAR(255) NOT NULL,
  `tb_categoria_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_curso_tb_categoria_idx` (`tb_categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_curso_tb_categoria`
    FOREIGN KEY (`tb_categoria_id`)
    REFERENCES `db_cursoDaMinhaVida`.`tb_categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into tb_categoria (nome, periodo, carga_horaria)
values ("Iniciante","Matutino","220 horas");
insert into tb_categoria (nome, periodo, carga_horaria)
values ("Intermediário","Vespertino","240 horas");
insert into tb_categoria (nome, periodo, carga_horaria)
values ("Avançado","Noturno","440 horas");


insert into tb_curso (nome, valor, vagas, professor, dias_da_semana, tb_categoria_id)
values ("Lógica de Programação", 40.99, 200, "Matheus Oliveira", "Segunda e Quarta", 1);
insert into tb_curso (nome, valor, vagas, professor, dias_da_semana, tb_categoria_id)
values ("Introdução ao Java", 59.99, 200, "Luís Guerreiro", "Terça e Quinta", 2);
insert into tb_curso (nome, valor, vagas, professor, dias_da_semana, tb_categoria_id)
values ("Integração Spring e DB", 89.99, 120, "Rafael Queiróz", "Sexta", 3);
insert into tb_curso (nome, valor, vagas, professor, dias_da_semana, tb_categoria_id)
values ("Java Full Stack", 120.99, 40, "Jacqueline Hernandes", "Segunda à Sexta", 3);

select * from tb_curso where valor > 50;

select * from tb_curso where valor between 3 and 60;

select * from tb_curso where nome like "%J%";

select * from
tb_curso inner join tb_categoria
on tb_curso.tb_categoria_id = tb_categoria.id;

select * from tb_curso where tb_categoria_id = 3;






